apiVersion: v1
kind: Service
metadata:
  name: kaiburr-app-service
spec:
  type: NodePort # This makes the app accessible from outside the cluster
  selector:
    app: kaiburr-task-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080